import Link from "next/link";
import { ArrowRight, Check, FileCheck2, Landmark, ReceiptText } from "lucide-react";
import { JourneySteps, ProgressLine } from "@/components/layout/WorkspaceUI";
import { TAX_CATEGORIES } from "@/lib/taxation/categories";

export const formatTaxMoney = (value) => value == null ? "Not supplied" : `₹${Math.round(value).toLocaleString("en-IN")}`;

export function RegimeCards({ tax, selected, onChoose, busy }) {
  return <div className="fp-regime-panels">{["old", "new"].map((regime) => <section key={regime} className="fp-regime-panel" data-lower={tax.available && tax.recommended === regime} aria-label={`${regime === "old" ? "Old" : "New"} regime summary`}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-medium">{regime === "old" ? "Old" : "New"} regime</h2>{tax.available && tax.recommended === regime && <span className="rounded-full bg-white px-3 py-1 text-xs text-primary">Lower salary estimate</span>}</div><p className="fp-regime-amount">{tax.available ? formatTaxMoney(tax[regime].tax) : "—"}</p><p className="text-xs text-muted-foreground">Estimated annual salary tax · includes applicable cess</p>{tax.available && <dl><div><dt>Taxable salary</dt><dd>{formatTaxMoney(tax[regime].taxableIncome)}</dd></div><div><dt>Eligible deductions</dt><dd>{formatTaxMoney(Object.values(tax[regime].deductions).reduce((sum, value) => sum + value, 0))}</dd></div><div><dt>Rebate</dt><dd>{formatTaxMoney(tax[regime].rebate)}</dd></div></dl>}{onChoose && <button type="button" onClick={() => onChoose(regime)} disabled={busy || !tax.available} aria-pressed={selected === regime} className={`fp-button mt-4 w-full ${selected === regime ? "!border-primary !bg-primary !text-white" : ""}`}>{selected === regime && <Check size={16} />}{selected === regime ? "Saved planning choice" : `Choose ${regime} regime`}</button>}</section>)}</div>;
}

export function PreparationJourney({ report, filingChecklist = {} }) {
  const reviewed = section => { const item = report.checklist.find(c => c.section === section); return Boolean(item && item.completed === item.total); };
  return <JourneySteps label="Tax preparation journey" steps={[{label:"Gather records",detail:"Salary and supporting proofs",complete:reviewed("salary-documents") && reviewed("banking-investments")},{label:"Reconcile",detail:"Review AIS and declared payments",complete:filingChecklist.tax_paid === true},{label:"Review estimates",detail:"Compare and choose a regime",complete:report.filing.regime !== "undecided"},{label:"Record filing status",detail:"Self-reported portal status",complete:report.filing.status === "filed"}]} />;
}

export function DeductionRows({ report, labels }) {
  const sections = {hra:"rent-hra",standard:"salary-documents",employerNps:"salary-documents"};
  return <div className="fp-card overflow-hidden"><div className="border-b border-border p-5 sm:p-6"><h2 className="text-xl font-medium">Your deductions, with their records.</h2><p className="mt-2 text-sm text-muted-foreground">Eligible amounts from the saved salary estimate. Review a section to edit its inputs and supporting proofs.</p></div><div className="divide-y divide-border">{Object.entries(labels).map(([key,label])=> {const section = sections[key] || "tax-saving-proofs"; const count = report.documents.filter(doc=>doc.section === section).length; return <div key={key} className="flex flex-wrap items-center gap-4 p-5 sm:px-6"><span className="fp-icon"><ReceiptText size={18} /></span><div className="min-w-0 flex-1"><h3 className="text-sm font-medium">{label}</h3><p className="mt-1 text-xs text-muted-foreground">{count ? `${count} section document${count === 1 ? "" : "s"} attached · review eligibility` : "No section documents attached"}</p></div><div className="text-right"><p className="text-xs text-muted-foreground">Saved eligible amount · old regime</p><p className="mt-1 text-lg font-medium tabular-nums">{report.tax.available ? formatTaxMoney(report.tax.old.deductions[key] || 0) : "Needs valid inputs"}</p></div><Link className="fp-button" href={`/taxation/${section}?year=${report.year}`}>Review<ArrowRight size={15} /></Link></div>;})}</div></div>;
}

export function TaxReadiness({ report }) {
  return <section className="fp-card p-5 sm:p-6"><div className="mb-5 flex items-center gap-2"><FileCheck2 size={18} className="text-primary" /><h2 className="text-lg font-medium">Records to review</h2></div><div className="space-y-5">{report.checklist.map(item=><Link key={item.section} href={`/taxation/${item.section}?year=${report.year}`} className="block"><div className="mb-2 flex justify-between gap-3 text-sm"><span>{TAX_CATEGORIES.find(c=>c.slug===item.section)?.title}</span><span className="text-muted-foreground">{item.completed}/{item.total}</span></div><ProgressLine value={item.completed / item.total * 100} label="Manually reviewed" /></Link>)}</div></section>;
}

export function TaxPaymentSummary({ report }) {
  const reconciliation = report.reconciliation;
  return <section className="fp-card p-5 sm:p-6"><div className="flex items-center gap-2"><Landmark size={18} className="text-primary" /><h2 className="text-lg font-medium">Liability and declared payments</h2></div><div className="my-6 grid gap-5 sm:grid-cols-3">{[["Salary tax estimate",reconciliation.available ? reconciliation.liability : null],["Annual TDS declared",report.filing.annualTds],["Advance tax declared",report.filing.advanceTax]].map(([label,value])=><div key={label}><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-medium tabular-nums">{formatTaxMoney(value)}</p></div>)}</div><div className="rounded-xl bg-secondary p-5">{reconciliation.available ? <><p className="text-sm text-muted-foreground">{reconciliation.balance > 0 ? "Balance against salary estimate" : "Excess declared payments"}</p><p className="mt-2 text-3xl font-medium tabular-nums">{formatTaxMoney(reconciliation.balance > 0 ? reconciliation.balance : reconciliation.excess)}</p></> : <p className="text-sm text-muted-foreground">{reconciliation.reason}</p>}</div><p className="mt-4 text-xs leading-relaxed text-muted-foreground">Annual totals are self-reported. Excess payments are not an approved refund. Other income, credits, fees and interest can change the final balance.</p><Link className="fp-primary-link mt-5" href={`/taxation/compliance-filing?year=${report.year}`}>Review payments and filing<ArrowRight size={15} /></Link></section>;
}
