"use client";

import { useState } from "react";
import Link from "next/link";
import BrandMark from "@/components/layout/BrandMark";
import { ArrowDownLeft, ArrowRight, ArrowUpRight, CalendarDays, Check, ChevronDown, CircleHelp, FileText, LayoutDashboard, MessageSquare, Target, Wallet } from "lucide-react";

const features = [
  { icon: Wallet, label: "A clearer everyday", title: "Know where your money goes.", body: "Import your bank statement, review the transactions, and bring your spending into one organised view." },
  { icon: FileText, label: "A calmer tax season", title: "Keep the whole year together.", body: "Compare salary tax regimes, organise your proofs, and revisit the numbers for each financial year." },
  { icon: Target, label: "Room for what matters", title: "Make a plan you can follow.", body: "Set budgets and savings goals. Explore how a planned purchase or EMI could fit into your monthly cash flow." },
  { icon: MessageSquare, label: "A little guidance", title: "Ask your financial Copilot.", body: "Explore questions about your saved financial information with AI explanations and built-in calculations." },
  { icon: CalendarDays, label: "Less to remember", title: "Give important dates a home.", body: "Keep reminders and goal milestones in your calendar, with an export for the calendar you already use." },
  { icon: LayoutDashboard, label: "The bigger picture", title: "Look back. Move forward.", body: "Browse previous months and download reports to understand the progress behind your everyday decisions." },
];

const faqs = [
  { q: "Who is Finpilot for?", a: "Finpilot brings spending, budgets, goals, and Indian salary tax planning into one workspace. It is especially useful when you want to organise your own records and review them before making a decision." },
  { q: "How do I add my transactions?", a: "Add them manually or import a CSV, Excel file, PDF statement, or statement image. You can review extracted transactions and change their categories before importing. Document layouts and image quality can affect extraction." },
  { q: "Does Finpilot file my tax return?", a: "Finpilot helps you organise tax information, estimate salary tax, compare regimes, and export your records. It does not submit a tax return or replace a professional review of complex income." },
  { q: "Do I need to connect my bank account?", a: "No. You can start with a statement upload or manual transactions. Live bank feeds are not required for the current workspace." },
];

function Brand() {
  return <Link href="/" className="inline-flex items-center gap-2.5 text-xl font-semibold tracking-tight text-[#202a25]" aria-label="Finpilot home"><BrandMark />finpilot<span className="text-[#8ba88e]">.</span></Link>;
}

function WorkspacePreview() {
  return (
    <div className="relative mx-auto w-full max-w-[560px]">
      <div className="rounded-[24px] border border-[#dbe3da] bg-white p-5 sm:p-7">
        <div className="mb-7 flex items-center justify-between border-b border-[#edf0eb] pb-5"><div className="flex items-center gap-2.5"><span className="flex size-8 items-center justify-center rounded-lg bg-[#edf2eb] text-[#214d43]"><LayoutDashboard size={16} strokeWidth={1.7} /></span><span className="text-sm font-medium">Your overview</span></div><span className="rounded-full border border-[#e3e8df] px-2.5 py-1 text-[10px] uppercase tracking-[.12em] text-[#738078]">Sample workspace</span></div>
        <p className="text-xs text-[#738078]">Available this month</p>
        <div className="mt-2 flex flex-wrap items-end justify-between gap-3"><p className="text-[38px] font-medium leading-none tracking-[-.045em] sm:text-[44px]">₹50,700<span className="text-[#a5afa5]">.00</span></p><span className="rounded-full bg-[#edf2eb] px-2.5 py-1 text-[11px] font-medium text-[#214d43]">Income − spending</span></div>
        <div className="mt-6 grid grid-cols-2 gap-4"><div className="flex items-center gap-2.5"><span className="flex size-8 items-center justify-center rounded-full bg-[#edf2eb] text-[#527759]"><ArrowDownLeft size={15} /></span><div><p className="text-[11px] text-[#738078]">Income</p><p className="text-sm font-medium">₹92,500</p></div></div><div className="flex items-center gap-2.5"><span className="flex size-8 items-center justify-center rounded-full bg-[#f6eee9] text-[#a67860]"><ArrowUpRight size={15} /></span><div><p className="text-[11px] text-[#738078]">Spending</p><p className="text-sm font-medium">₹41,800</p></div></div></div>
        <div className="mt-7 rounded-2xl bg-[#f6f7f4] px-4 pb-3 pt-5"><div className="flex justify-between text-[11px] text-[#738078]"><span>Monthly cash flow</span><span>Income / spending</span></div><div className="mt-5 flex h-28 items-end justify-between gap-4 px-2" aria-hidden="true">{[[68, 43], [86, 50], [75, 44], [97, 68], [83, 47], [100, 45]].map(([income, spend], i) => <div key={i} className="flex h-full flex-1 items-end justify-center gap-1.5"><div className="w-3.5 rounded-t-md bg-[#214d43] sm:w-5" style={{ height: income + "%" }} /><div className="w-3.5 rounded-t-md bg-[#cfdbc9] sm:w-5" style={{ height: spend + "%" }} /></div>)}</div><div className="mt-3 flex justify-between px-1 text-[10px] text-[#89938a]">{["Apr", "May", "Jun", "Jul", "Aug", "Sep"].map(month => <span key={month}>{month}</span>)}</div></div>
        <div className="mt-5 flex items-center justify-between gap-3 rounded-xl border border-[#e3e8df] p-3.5"><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl bg-[#edf2eb] text-[#214d43]"><Target size={17} strokeWidth={1.7} /></span><div><p className="text-xs font-medium">A little closer to your goals</p><p className="mt-0.5 text-[11px] text-[#738078]">Your progress, all in one place.</p></div></div><ArrowUpRight size={16} className="text-[#738078]" /></div>
      </div>
      <div className="ml-5 mt-4 flex items-center gap-3 rounded-2xl border border-[#dbe3da] bg-[#edf2eb] px-4 py-3.5 sm:ml-12"><span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-white text-[#214d43]"><Check size={15} /></span><p className="text-xs leading-relaxed text-[#526459]">A place for your money today.<br /><span className="font-medium text-[#214d43]">And the plans you are making for tomorrow.</span></p></div>
    </div>
  );
}

export default function LandingPage() {
  const [openFaq, setOpenFaq] = useState(null);
  return (
    <div className="min-h-screen bg-[#f6f7f4] text-[#202a25] selection:bg-[#cfdbc9]">
      <header className="border-b border-[#e2e7de] bg-[#f6f7f4]/95"><div className="mx-auto flex min-h-20 max-w-7xl items-center justify-between gap-4 px-5 sm:px-8 lg:px-12"><Brand /><nav className="hidden items-center gap-8 text-sm text-[#647268] md:flex" aria-label="Main navigation"><a className="transition-colors hover:text-[#214d43]" href="#features">The workspace</a><a className="transition-colors hover:text-[#214d43]" href="#how-it-works">How it works</a><a className="transition-colors hover:text-[#214d43]" href="#faq">Questions</a></nav><div className="flex items-center gap-2 sm:gap-5"><Link href="/auth/login" className="px-2 py-2.5 text-sm font-medium hover:text-[#526f59]">Sign in</Link><Link href="/auth/signup" className="hidden items-center gap-2 rounded-xl bg-[#214d43] px-4 py-2.5 text-sm font-medium text-white transition-colors hover:bg-[#193e35] sm:inline-flex">Get started <ArrowUpRight size={16} /></Link></div></div></header>
      <main>
        <section className="mx-auto grid max-w-7xl items-center gap-14 px-5 py-14 sm:px-8 sm:py-20 lg:grid-cols-[1fr_1fr] lg:gap-16 lg:px-12 lg:py-24">
          <div><div className="mb-7 inline-flex items-center gap-2 text-[11px] font-medium uppercase tracking-[.2em] text-[#617a63]"><span className="h-px w-7 bg-[#819982]" /> Your personal finance workspace</div><h1 className="max-w-xl text-[48px] font-medium leading-[1.08] tracking-[-.055em] sm:text-[60px] lg:text-[66px]">Money, with a<br /><span className="text-[#6e856c]">little more clarity.</span></h1><p className="mt-7 max-w-md text-base leading-[1.8] text-[#738078]">Your spending, taxes, and future plans. Thoughtfully brought together, so you can feel more in control of what comes next.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/auth/signup" className="inline-flex items-center justify-center gap-4 rounded-xl bg-[#214d43] px-6 py-3.5 text-sm font-medium text-white transition-colors hover:bg-[#193e35]">Create your workspace <ArrowRight size={17} strokeWidth={1.7} /></Link><a href="#features" className="inline-flex items-center justify-center gap-2 rounded-xl border border-[#dbe3da] px-5 py-3.5 text-sm font-medium hover:bg-white">Take a look <ArrowDownLeft size={16} className="-rotate-45" /></a></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-xs text-[#738078]"><span className="inline-flex items-center gap-1.5"><Check size={14} className="text-[#527759]" /> Built for Indian finances</span><span className="inline-flex items-center gap-1.5"><Check size={14} className="text-[#527759]" /> Start with your own records</span></div></div>
          <WorkspacePreview />
        </section>
        <section id="features" className="scroll-mt-8 border-y border-[#e2e7de] bg-white"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-20 lg:px-12"><div className="mb-10 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-[11px] font-medium uppercase tracking-[.18em] text-[#738078]">One thoughtfully connected space</p><h2 className="mt-3 text-3xl font-medium tracking-[-.04em] sm:text-4xl">Less scattered.<br />More considered.</h2></div><p className="max-w-sm text-sm leading-relaxed text-[#738078]">Small everyday decisions and bigger financial plans deserve the same clear view.</p></div><div className="grid gap-x-8 gap-y-1 md:grid-cols-2 lg:grid-cols-3">{features.map(({ icon: Icon, label, title, body }) => <article key={title} className="border-t border-[#e4e9e1] py-7"><span className="mb-6 flex size-11 items-center justify-center rounded-2xl bg-[#edf2eb] text-[#214d43]"><Icon size={21} strokeWidth={1.7} /></span><p className="mb-2 text-[10px] uppercase tracking-[.15em] text-[#738078]">{label}</p><h3 className="text-lg font-medium tracking-tight">{title}</h3><p className="mt-3 text-sm leading-[1.8] text-[#738078]">{body}</p></article>)}</div></div></section>
        <section id="how-it-works" className="mx-auto max-w-7xl scroll-mt-8 px-5 py-16 sm:px-8 sm:py-20 lg:px-12"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-[11px] font-medium uppercase tracking-[.18em] text-[#738078]">Make yourself at home</p><h2 className="mt-3 max-w-sm text-3xl font-medium leading-tight tracking-[-.04em] sm:text-4xl">A fresh perspective.<br />A familiar starting point.</h2><Link href="/auth/signup" className="mt-7 inline-flex items-center gap-3 text-sm font-medium text-[#214d43]">Let’s get organised <ArrowRight size={16} /></Link></div><div>{[{ title: "Bring your records", body: "Start with a bank statement, add your income, or enter a few transactions." }, { title: "Review the details", body: "Check imported records, choose categories, and fill in the information that matters to you." }, { title: "Find your next step", body: "Explore your month, organise tax proofs, and make space for your next goal." }].map((step, i) => <div key={step.title} className="flex gap-5 border-b border-[#dfe5db] py-6 first:pt-0"><span className="text-xs text-[#879580]">0{i + 1}</span><div><h3 className="text-lg font-medium tracking-tight">{step.title}</h3><p className="mt-2 max-w-lg text-sm leading-relaxed text-[#738078]">{step.body}</p></div></div>)}</div></div></section>
        <section id="faq" className="border-t border-[#e2e7de] bg-white"><div className="mx-auto grid max-w-7xl gap-9 px-5 py-16 sm:px-8 sm:py-20 lg:grid-cols-[.8fr_1.2fr] lg:px-12"><div><CircleHelp size={26} strokeWidth={1.5} className="mb-4 text-[#7b9077]" /><h2 className="text-3xl font-medium tracking-[-.04em]">A few good questions.</h2><p className="mt-3 text-sm text-[#738078]">A little more clarity before you begin.</p></div><div>{faqs.map((faq, i) => <div key={faq.q} className="border-b border-[#e4e9e1]"><button type="button" onClick={() => setOpenFaq(openFaq === i ? null : i)} aria-expanded={openFaq === i} aria-controls={"faq-answer-" + i} className="flex w-full items-center justify-between gap-4 py-5 text-left text-sm font-medium"><span>{faq.q}</span><ChevronDown size={17} className={"shrink-0 text-[#738078] transition-transform " + (openFaq === i ? "rotate-180" : "")} /></button>{openFaq === i && <p id={"faq-answer-" + i} className="pb-5 text-sm leading-[1.8] text-[#738078]">{faq.a}</p>}</div>)}</div></div></section>
        <section className="mx-auto max-w-7xl px-5 py-12 sm:px-8 sm:py-16 lg:px-12"><div className="flex flex-col justify-between gap-8 rounded-[24px] bg-[#214d43] px-7 py-10 text-white sm:px-12 sm:py-12 md:flex-row md:items-center"><div><p className="mb-3 text-[11px] uppercase tracking-[.18em] text-[#c0d1bf]">Your next chapter</p><h2 className="text-3xl font-medium leading-tight tracking-[-.04em] sm:text-4xl">Make room for<br />a clearer financial life.</h2></div><Link href="/auth/signup" className="inline-flex w-fit items-center gap-5 rounded-xl bg-[#edf2eb] px-6 py-3.5 text-sm font-medium text-[#214d43] transition-colors hover:bg-white">Start with Finpilot <ArrowUpRight size={17} /></Link></div></section>
      </main>
      <footer className="border-t border-[#e2e7de]"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 px-5 py-8 sm:flex-row sm:items-center sm:px-8 lg:px-12"><Brand /><p className="text-xs text-[#738078]">A little clarity goes a long way.</p><p className="text-xs text-[#8a958b]">© {new Date().getFullYear()} Finpilot</p></div></footer>
    </div>
  );
}
